# Uncomment the next line to define a global platform for your project
platform :ios, ’10.0’

target 'Roommates-N-Bills' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Roommates-N-Bills
	pod ‘SnapKit’, ‘~> 4.0.0’
	pod ‘Hero’
	pod ‘DropDown’

end
